from . import ng_hr_payroll
from . import ng_hr_salary
from . import ng_hr_payroll_overtime
from . import ng_hr_union
from . import ng_hr_terminal
from . import res_company
from . import ng_hr_holiday
from . import ng_hr_contract
from . import ng_hr_payslip
from . import salary_template
